### ISSUE TITLE
Compilation error, in msvc

### ISSUE THREAD

**Issue by bizehao** [ericniebler/ustdex#1]
error C2995: "unknown-type ustdex::_apply(Fn &&,Tup &&) noexcept(<expr>)": function template has been defined

**Comment by bizehao** [comment]
clang Can be compiled and passed

**Comment by ericniebler** [comment]
I'm not supporting msvc at the moment, although I would gladly take a patch if you find the problem.

**Comment by bizehao** [comment]
This is my modification. It can be compiled and run. Because the latest version has changed too much, I can't provide a PR, so I can only provide the changed code. Sorry.

```
template <class Fn, class Tup, std::size_t... Idx, class... Ts>
USTDEX_INLINE USTDEX_HOST_DEVICE
constexpr auto _apply_impl(
  Fn &&fn,
  Tup &&tup,
  const _tuple<std::index_sequence<Idx...>, Ts...>&
) noexcept(_v<_mvalue<_nothrow_callable<Fn, _copy_cvref_t<Tup, Ts>...>>>)
  -> decltype(DECLVAL(Fn)(DECLVAL(_copy_cvref_t<Tup, Ts>)...)) {
  return std::invoke(
    std::forward<Fn>(fn),
    static_cast<_copy_cvref_t<Tup, _box<Ts, Idx>> &&>(tup)._value...);
}

template <class Fn, class Tup>
USTDEX_INLINE USTDEX_HOST_DEVICE
constexpr auto _apply(Fn &&fn, Tup &&tup) noexcept(noexcept(_apply_impl(std::forward<Fn>(fn), std::forward<Tup>(tup), tup))) {
  return _apply_impl(std::forward<Fn>(fn), std::forward<Tup>(tup), tup);
}
```

**Comment by ericniebler** [comment]
Can you try now? I've replaced the use of ADL with a member function.

**Comment by ericniebler** [comment]
msvc works now. see: https://github.com/ericniebler/ustdex/actions/runs/8730108676

**Comment by bizehao** [comment]
yes, it`s ok!   i'm learning it
